/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mysqljava;


import Controller.CandidateController;

public class App {
    public static void main(String[] args) {


        //new CandidateController().listAllCandidates();
        new CandidateController().getCandidateById(115);

    }

}
