/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mysqljava;


import Database.DbQueries;
import Model.Candidate;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {


        new DbQueries().listAllCandidates();

    }

}
